### PR TITLE
fix: resize python and dotnet images.

### PR DESCRIPTION
**Pull request by divy9881**
Screenshot (169)

### CODE REVIEW

**Comment by hsluoyz** [comment]
lgtm

**Comment by hsluoyz** [comment]
@divy9881 is Casbin-CPP still "under-development"? Should we advance to a more finalized stage like "beta-test", "public-review", etc.?

**Comment by divy9881** [comment]
Yeah, we can turn the status into beta-test

**Comment by hsluoyz** [comment]
@divy9881 please make a PR.

**Pull request merged**
