### PR TITLE
feat: Add addnamedmatchingfunc python example

### PR DESCRIPTION
**Pull request by teresafds**
This PR adds python code snippet on RoleManager API docs page for add_named_matching_func methods

### CODE REVIEW

**Comment by hsluoyz** [comment]
@teresafds fix:

image

**Comment by teresafds** [comment]
@hsluoyz Apologies for the inconvenience. Error fixed after updating commit message

**Comment by hsluoyz** [comment]
@teresafds thanks for making PRs these days. Can you make future PRs to the v2 docs? https://github.com/casbin/casbin-website-v2 . We are migrating everything to v2 docs: https://casbin.io/ and gradually ceasing the development on v1 docs.

**Comment by teresafds** [comment]
@hsluoyz Thanks for the clarification. I've created a PR in new casbin-website repo [here](https://github.com/casbin/casbin-website-v2/pull/9 )

**Comment by hsluoyz** [comment]
@teresafds great!

**Pull request closed without merging**
