### PR TITLE
feat: Add small logo icons at the left of each button

### LINKED ISSUE #230: Add small logo icons at the left of each button
See:

image

Add each language's logo before text.

### PR DESCRIPTION
**Pull request by turbodog03**
image

resolve #230

### CODE REVIEW

**Comment by hsluoyz** [comment]
@turbodog03

1. The icons can be larger.
2. Most icons are not vertically aligned with the text (too high).
3. The icons are obscure. Plz use high-resolution PNG images or even SVG.

Plz fix.

**Comment by hsluoyz** [comment]
@turbodog03 this time looks much better! A few possible improvements:

1. PHP uses this logo: https://commons.wikimedia.org/wiki/File:PHP-logo.svg
2. DotNet uses this: https://github.com/dotnet/brand/blob/main/logo/dotnet-logo.svg

**Comment by turbodog03** [comment]
> @turbodog03 this time looks much better! A few possible improvements:
> 
> 1. PHP uses this logo: https://commons.wikimedia.org/wiki/File:PHP-logo.svg
> 2. DotNet uses this: https://github.com/dotnet/brand/blob/main/logo/dotnet-logo.svg

thanks! I've inproved it just now.

**Comment by hsluoyz** [comment]
lgtm

**Pull request merged**
