### PR TITLE
fix: Fix code snippet missing

### PR DESCRIPTION
**Pull request by ErikQQY**
Signed-off-by: ErikQQY <2283984853@qq.com>

### CODE REVIEW

**Comment by hsluoyz** [comment]
@ErikQQY it doesn't look good..

image

**Comment by hsluoyz** [comment]
@ErikQQY any update?

**Comment by Selflocking** [comment]
Seems like these come from https://casbin.org/docs/en/policy-subset-loading
I think only the first paragraph is useful, the other two are not.
The homepage should briefly describe the advantages of casbin, not how to use it.

**Comment by hsluoyz** [comment]
@Selflocking good points, closed here.

**Pull request closed without merging**
