### PR TITLE
feat: add multiple type useage to doc

### PR DESCRIPTION
**Pull request by tangyang9464**
Signed-off-by: tangyang9464 <tangyang9464@163.com>

associate feature: [casbin#838](https://github.com/casbin/casbin/pull/838)

### CODE REVIEW

**Comment by hsluoyz** [comment]
@ErikQQY plz give some suggestions.

**Review by ErikQQY — COMMENTED** [review]
LGTM, I think add the test example of [multiple_policy_definitions_model](https://github.com/casbin/casbin/blob/master/examples/multiple_policy_definitions_model.conf) directly to docs would be better explain the new feature. Besides, plz note the spacing after punctuation marks in every sentence.

**Comment by tangyang9464** [comment]
> LGTM, I think add the test example of [multiple_policy_definitions_model](https://github.com/casbin/casbin/blob/master/examples/multiple_policy_definitions_model.conf) directly to docs would be better explain the new feature. Besides, plz note the spacing after punctuation marks in every sentence.

space is ok.

**Comment by hsluoyz** [comment]
@tangyang9464 yes, plz change the spaces:

image

**Comment by tangyang9464** [comment]
> change

changed

**Comment by tangyang9464** [comment]
> @tangyang9464 yes, plz change the spaces:
> 
> image

changed

**Comment by hsluoyz** [comment]
@tangyang9464 change ALL places

**Comment by tangyang9464** [comment]
> @tangyang9464 change ALL places

sry. changed now

**Pull request merged**
